### ISSUE TITLE
Pull to refresh on desktop

### ISSUE THREAD

**Issue by trobbertze** [IjzerenHein/famous-flex#107]
Hi Hein

In the FlexScrollView Pull to refresh does not seem to work with a normal 2 finger gesture in any desktop browser.

Down press and drag works in Chrome dev tools in device mode.

A quick guess, I have not really dug into it, is that you are only listening to touch events and not scroll events.  Any idea if there is a quick hack I can use to fix this?

**Comment by IjzerenHein** [comment]
Hey Theo,

In order to enable that you need to set `mouseMove` to true.
Unfortunately, pull to refresh is not possible using `mousewheel` events, which are fired when you use the (Mac) trackpad. That's because of the nature of 'mousewheel' events, which don't have a 'start' and 'end' phase like mousedown/up and touchstart/touchend has.

**Comment by IjzerenHein** [comment]
ping @trobbertze 
Can I close this?

**Comment by trobbertze** [comment]
Sure thing
