### ISSUE TITLE
FlexScrollView ignores Z-translate  

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#46]
Hi there, 
After our conversation at stackoverflow (http://stackoverflow.com/questions/28147595/z-translate-is-ignored-by-gridlayout-view) I did try to rewrite my code using FlexScrollView. Same result: in Chrome surface ignores z-translate and IE just shows black screen. Any ideas?

define(function(require, exports, module) {
    var Engine     = require("famous/core/Engine");
    var Surface    = require("famous/core/Surface");
    var View      = require("famous/core/View");
    var ContainerSurface = require("famous/surfaces/ContainerSurface");
	var StateModifier = require('famous/modifiers/StateModifier');
	var Transform      = require("famous/core/Transform");
	var Utility      = require("famous/utilities/Utility");
	var Flex = require("famous-flex/src/FlexScrollView");
	var CollectionLayout = require("famous-flex/src/layouts/CollectionLayout");
	
	var mainContext = Engine.createContext();
		mainContext.setPerspective(1000);
		
	var flex = new Flex({
		autoPipeEvents: true,
		mouseMove: true,
		direction: Utility.Direction.X
	});
	
	var cont1 = new ContainerSurface();
	cont1.context.setPerspective(1000);
	var surf1 = new Surface({size:[400, 200],properties:{background:'red'}})
	var mod1 = new StateModifier();
	cont1.add(mod1).add(surf1);
	
	flex.push(cont1);
	flex.push(new Surface({size:[400, 200],properties:{background:'green'}}));
	flex.push(new Surface({size:[400, 200],properties:{background:'blue'}}));
	
	Engine.on('click', function(){
		mod1.setTransform(Transform.translate(0,5,999), {duration:1000});
	});
    mainContext.add(flex);
});

**Comment by IjzerenHein** [comment]
Hi, can you create a demo I can view online?
Also, I'm not quite sure I understand what you are trying achieve here.

**Comment by Qvatra** [comment]
here is example: https://dl.dropboxusercontent.com/u/49691996/FamousDemo/kit/examples/views/flex/example.html

I want to be able to move an item closer using perspective.
in this case I want red surface move closer after click event.

**Comment by IjzerenHein** [comment]
Right, this issue is related to #36.

Apparently, when a DIV exists with a width and height of 0, the browser does not handle perspective in the way you expect. The famo.us ScrollView and the FlexScrollView both use a so called famo.us 'Group' for optimized scrolling and this component causes the problem. If you look in the DOM you will see a DIV with both a width and height of 0px. When you manually set those values to the actual width, the perspective does work. It seems to be both famo.us and browser related. I asked the fellow that reported #36 to report this to famo.us. I'm not sure if he has done so, but you could have a look.

Here was my full response regarding this matter:

I have investigated the problem and found that the problem lies in the Group component of famo.us and not specifically in famous-flex. The problem also occurs when you add your Bubble-view to a stock famo.us Scrollview (which uses the same optimized group-scrolling as the flex-scrollview).
It seems that the browser calculates the height/width differently when the div has a parent div with a width and height of 0px. Which is what famo.us inserts into the DOM when you use a Group.

Here is the relevant famo.us code (famous/core/Group.js):

```javascript
/**
     * Apply changes from this component to the corresponding document element.
     *
     * @private
     * @method commit
     *
     * @param {Object} context update spec passed in from above in the render tree.
     */
    Group.prototype.commit = function commit(context) {
        var transform = context.transform;
        var origin = context.origin;
        var opacity = context.opacity;
        var size = context.size;
        var result = Surface.prototype.commit.call(this, {
            allocator: context.allocator,
            transform: Transform.thenMove(transform, [-origin[0] * size[0], -origin[1] * size[1], 0]),
            opacity: opacity,
            origin: origin,
            //size: Group.SIZE_ZERO // this causes the problem
            size: context.size // this fixes it
        });
        if (size[0] !== this._groupSize[0] || size[1] !== this._groupSize[1]) {
            this._groupSize[0] = size[0];
            this._groupSize[1] = size[1];
            this.context.setSize(size);
        }
        this.context.update({
            transform: Transform.translate(-origin[0] * size[0], -origin[1] * size[1], 0),
            origin: origin,
            size: size
        });
        return result;
    };
```

Now perhaps this can be fixed through (hacky) workarounds, but I'd rather not go down that route. I would suggest submitting it to famo.us with a clearly defined test-case. And otherwise I would revise your solution and try to solve it differently. Also note that there is no such thing as 'true-sized' views. True-size only applies to Surfaces. The surface creates a div and then the DOM calculates the width/height for the surface. A view does not correspond to anything in the DOM.

**Comment by Qvatra** [comment]
The workaround is simple as just adding small initial value of z-translation:

	var mod1 = new StateModifier({
		transform: Transform.translate(0,0,0.01)
	});

**Comment by IjzerenHein** [comment]
Really? Oh wow, that's freaky. That certainly smells like a browser bug..

**Comment by Qvatra** [comment]
yep, see this one again for details: http://stackoverflow.com/questions/28147595/z-translate-is-ignored-by-gridlayout-view

**Comment by IjzerenHein** [comment]
Hi, please close this issue if you feel it was answered satisfactory.
