### ISSUE TITLE
bug report for layoutContext

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#68]
Hello
here is codepen example where I can see odd behavior of the custom layout function: http://codepen.io/Qvatra/pen/QwQmOW

1) line 57: 'translate: [0, 0, 0.01]'. I expect to see that all surfaces from dataSource will go to (0,0,0.01) position but I see that each surface positioned below the previous one.
2) line 56: 'size: [context.size[0], 100]'. I expect that this will change width for all surfaces to the width of outer container but it doesn't.
3) in documentation for layoutContext in layoutContext.prev() section in example you have a typo: there is 'transform: [0, height, 0]' and should be 'transLATE: [0, height, 0]'
4) this is not related to layoutContext but I also don't understand why in my codepen example (line 27, 28) if I set origin and align to [0.5,0.5] i don't see my grey container at the center.

**Comment by IjzerenHein** [comment]
Hi, let me answer question **1** directly, I'll get back on the other ones.

You've forgotten to include the 'famous/core/famous.css' file. This file is very important as it contains css styles which enabled absolute positioning on famous surfaces.

**Comment by IjzerenHein** [comment]
Hi, to answer the other questions:

2:
This happens because you have specified the size inside the surface as well. When you do that, famo.us overrides the size of the outside modifier (in this case the LayoutController). When you remove the 'size' from the Surface constructor it should be ok. This is just the way famo.us works.

3:
Thanks, I've fixed the typo's in the documentation.

4:
I think this is also because you have forgotten to include `famous/core/famous.css`.

**Comment by Qvatra** [comment]
great. thx

**Comment by IjzerenHein** [comment]
You're welcome! If you like this library, please show your support by giving it a star.
Cheers, Hein
