### ISSUE TITLE
reordering of sticky headers in Z direction when embedded within a scrollview

### ISSUE THREAD

**Issue by adamelk** [IjzerenHein/famous-flex#78]
I have a vertical scrollview that uses sticky headers.  I have placed this vertical scrollview within a horizontal, paginated scrollview, so my app can switch tabs between two vertical scrollviews.  For some reason, the ordering of the sticky headers in the Z direction is acting funky only when it is within the horizontal scrollview.  As I scroll, it constantly reorders the surfaces within the sticky header in the Z direction.  I even tried to translate the surfaces in the sticky header itself in the Z direction an enormous amount, something like 200 pixels, and it still is getting overlapped by other surfaces that it shouldn't.  When I put the vertical scrollview in my view without the paginated horizontal scrollview, it works fine and the ordering of the surfaces is perfect.  Any ideas what the problem might be?

**Comment by adamelk** [comment]
Actually I just isolated the error.  The actual problem is when my horizontal scrollview used a container to hide the overflow.  When I took out the container for the horizontal scrollview, it stopped the sticky headers from doing the weird reordering.

**Comment by ManuelOverdijk** [comment]
Did you use overflow:hidden on your container? There is a common bug when using oveflow:hidden on your surfaces. See https://famo.us/guides/pitfalls

**Comment by IjzerenHein** [comment]
Overflow: hidden does indeed cause z-indexing issues, be careful using it:
https://github.com/Famous/famous/issues/493

You could still use `useContainer: true`, but I would advise disabling 'overflow: hidden', by also setting 'overflow: {}', like this:

```javascript
var scrollView = new FlexScrollView({
  useContainer: true,
  container: {}
});
```

And then add a background surface behind the scrollviews and make sure that the scrollviews have different z-index so that the surfaces properly underlap and overlap. You have to be a bit creative with this, because of this annoying browser bug.

**Comment by adamelk** [comment]
Thank you I found a workaround in my app.
