### ISSUE TITLE
getDataSource from custom layout function?

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-flex#81]
hello,

I'm writing a layout function for a LayoutController and I want to have 2 loops through all nodes. First loop is straightforward as:
```
     node = context.next();
      	 index = 0;
      	 while (node && (index < ratios.length)) {
             // here I do calculations that are needed for positioning nodes at 2nd loop
          index++;
          node = context.next();
          nodes.push(node);    // <------------ workaround
        }
```
but the same code will not work again in the same function because  context.next() will return undefined. So as a workaround I create a nodes array and loop through it:
```
        nodes.forEach(function(node) {
          // set options here
          context.set(node, options);
        }) 
```
What is the right way to do this kind of constructions? Is there something like context.getDataSource() that I can use inside my function?

**Comment by IjzerenHein** [comment]
The interface for enumerating the nodes has been designed very strictly. The main reason for this is to support infinite/virtual scrolling scenarios properly.

The way to solve your problem is to indeed store the nodes in an array, and then you can re-iterate them as often as you want. There is however the restriction that you *must* layout (context.set) the nodes in the same order as you enumerated them. Also, if you want you can skip nodes, but cannot lay them out in a different order.

**Comment by Qvatra** [comment]
I've noticed that on 'layoutend' event fires right after the 1st loop but generally I need to fire it after the second loop (where I actually set options for my nodes).

Am I right here? 
Do you know how to solve the problem?
